services:
    db:
        container_name: todo4j-db
        restart: always
        image: postgres:17
        ports:
            - 5432:5432
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: todo4j_db
            POSTGRES_PASSWORD: secure-password
            POSTGRES_USER: todo4j-user
